#!/usr/bin/env python3
"""Convert the wordmark's <text> to outlines so its stripes clip correctly.

Codex's wordmark clips three stripes to the word "Tiger" with a `clipPath`
containing a `<text>` element. That is valid SVG and rsvg renders it exactly
right, but **flutter_svg does not apply a clipPath whose content is text**, so
in the app the stripes drew as three free-floating bars above the letters while
the letters stayed unstriped.

`assets/generated/SPEC.md` already anticipated this: "Convert text to paths
before packaging if exact cross-platform metrics are required." This does that,
mechanically, from the same font the app bundles. It is a packaging step, not a
design change: the geometry, colours and stripe positions are Codex's, untouched.

Converting also removes a second, quieter risk. Text SVG depends on the renderer
finding a font by name and matching its metrics; outlines depend on nothing.

Output goes beside the source as `*-flat.svg`, so the original stays the master
and can be regenerated by Codex without this being overwritten.

Usage: python3 scripts/flatten-wordmark.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from xml.sax.saxutils import escape

try:
    from fontTools.pens.svgPathPen import SVGPathPen
    from fontTools.ttLib import TTFont
except ImportError:
    print("fonttools is required: pip install fonttools", file=sys.stderr)
    raise SystemExit(1)

ROOT = Path(__file__).resolve().parent.parent
WORDMARKS = ROOT / "assets" / "generated" / "wordmark"

# The same file the app bundles, so the outlines match what the rest of the UI
# renders in this face.
FONT = ROOT / "client" / "assets" / "fonts" / "SpaceGrotesk-Bold.otf"

TEXT_RE = re.compile(
    r'<text\s+x="(?P<x>[-\d.]+)"\s+y="(?P<y>[-\d.]+)"'
    r'(?P<mid>[^>]*?)>(?P<body>[^<]*)</text>',
    re.S,
)
SIZE_RE = re.compile(r'font-size="([\d.]+)"')
FILL_RE = re.compile(r'fill="([^"]+)"')


def outline(font: TTFont, text: str, x: float, y: float, size: float) -> str:
    """The SVG path data for `text`, laid out at a baseline of (x, y)."""
    glyph_set = font.getGlyphSet()
    cmap = font.getBestCmap()
    units = font["head"].unitsPerEm
    scale = size / units

    parts: list[str] = []
    pen_x = x

    for char in text:
        name = cmap.get(ord(char))
        if name is None:
            continue
        pen = SVGPathPen(glyph_set)
        glyph_set[name].draw(pen)
        data = pen.getCommands()
        if data:
            # SVG y grows downward and font y grows upward, hence the flip.
            parts.append(
                f'<path transform="translate({pen_x:.3f} {y:.3f}) '
                f'scale({scale:.6f} {-scale:.6f})" d="{data}"/>'
            )
        pen_x += glyph_set[name].width * scale

    return "".join(parts)


CLIP_RE = re.compile(r"<clipPath\b.*?</clipPath>", re.S)


def flatten(source: Path, font: TTFont) -> str:
    svg = source.read_text()

    def replace(match: re.Match[str], *, bare: bool = False) -> str:
        x = float(match.group("x"))
        y = float(match.group("y"))
        mid = match.group("mid")
        body = match.group("body")

        size_match = SIZE_RE.search(mid)
        if size_match is None:
            # Nothing to lay out against, so leave it alone rather than guess.
            return match.group(0)

        paths = outline(font, body, x, y, float(size_match.group(1)))
        if bare:
            # A clipPath may only contain shapes, so no group wrapper here.
            # Wrapping them silently emptied the clip, which showed up as the
            # stripes escaping the letters entirely.
            return paths

        fill_match = FILL_RE.search(mid)
        fill = fill_match.group(1) if fill_match else "currentColor"

        # The label is kept on the group so nothing is lost to a reader that
        # was relying on the text content being present.
        return f'<g fill="{fill}" aria-label="{escape(body)}">{paths}</g>'

    # Clip paths first, and with no wrapper, then everything else.
    def flatten_clip(clip: re.Match[str]) -> str:
        return TEXT_RE.sub(lambda m: replace(m, bare=True), clip.group(0))

    svg = CLIP_RE.sub(flatten_clip, svg)
    return TEXT_RE.sub(replace, svg)


def main() -> int:
    if not FONT.exists():
        print(f"missing {FONT}", file=sys.stderr)
        return 1

    font = TTFont(FONT)
    written = 0

    for source in sorted(WORDMARKS.glob("*.svg")):
        if source.stem.endswith("-flat"):
            continue
        target = source.with_name(f"{source.stem}-flat.svg")
        target.write_text(flatten(source, font))
        print(f"  {target.relative_to(ROOT)}")
        written += 1

    if written == 0:
        print("no wordmarks found", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
